---
__common_packages:
  - autoconf
  - bash-completion
  - bzip2
  - curl
  - diffutils
  - dos2unix
  - epel-release
  - firewalld
  - gawk
  - gcc
  - git
  - grep
  - gzip
  - iotop
  - less
  - make
  - nano
  - nmap
  - ntp
  - ntpdate
  - openssl
  - tar
  - unzip
  - wget
  - whois
  - zip
  - unzip
