---

- name: check if Slack is installed?
  shell: "{{playbook_dir}}/roles/slack/scripts/grepSlack.sh -i={{ slack.version }}"
  register: slack_current_version
  changed_when: false
  failed_when: false
  become: yes

- debug:
    msg: "slack_current_version : {{ slack_current_version.stdout }}"

- block:

  - name: install the Slack packages
    package:
      name: "{{ item }}"
      state: present
    with_items:
      - "{{slack.url_rpm}}"
    when: slack_current_version.stdout is defined and slack.version not in slack_current_version.stdout
    become: yes

  when: slack_current_version.stdout == "" or slack_current_version.stdout | version_compare(slack.version, '>')
