---

- name: check if NPM is installed?
  shell: npm -v 2>&1
  register: current_version
  changed_when: false
  ignore_errors: true
  args:
    warn: no

- debug:
    msg: "current_version={{ current_version }}"

- block:

  - name: Ensure npm global packages are installed.
    npm:
      name: "{{ item.name | default(item) }}"
      version: "{{ item.version | default('latest') }}"
      global: yes
      state: latest
    with_items: "{{ npm_packages }}"
    ignore_errors: yes
    become: yes

  - name: Install packages from package.json.
    npm:
      path: "{{ npm.package_json_path }}"
    when: npm.package_json_path is defined and npm.package_json_path
    become: yes

  when: 
    - node_current_version is succeeded
    - node_current_version is defined
    - node_current_version.stdout == "" or node_current_version.stdout is version(npm.version, operator='>=', strict=True)
