---

- name: check if Sqlectron is installed?
  shell: "{{playbook_dir}}/roles/sqlectron/scripts/grepSqlectron.sh -i={{ sqlectron.version }}"
  register: sqlectron_current_version
  changed_when: false
  failed_when: false
  become: yes

- debug:
    msg: "sqlectron_current_version : {{ sqlectron_current_version.stdout }}"

- block:
  
  - name: install the Sqlectron packages
    package:
      name: "{{ item }}"
      state: present
    with_items:
      - "{{ sqlectron.url_rpm}}"
    become: yes

  when: sqlectron_current_version.stdout == "" or sqlectron_current_version.stdout | version_compare(sqlectron.version, '>')
