---

pip:
  version: 8.1.2
  user: "{{ ansible_env.USER | default(ansible_user) }}"

  #  Install a specific version of a package.
  #  - name: jslint
  #    version: 0.9.3
  #  Install the latest stable release of a package.
  #  - name: node-sass
  #  This syntax also works.
  #  - node-sass
  packages:
    - pip
