---

- name: check if Atom is installed?
  shell: "{{playbook_dir}}/roles/atom/scripts/grepAtom.sh -i={{ atom.version }}"
  register: atom_current_version
  changed_when: false
  failed_when: false
  become: yes

- debug:
    msg: "recommended_atom_version: {{ atom.version }}, atom_current_version : {{ atom_current_version.stdout }}"

- block:

  - debug:
      msg: "atom is not installed, or has a version prior to {{ atom.version }}"

  - name : uninstall older version
    package:
      name: atom
      state: absent
    become: yes

  - name: install the atom packages
    package:
      name: "{{ item }}"
      state: present
    with_items:
      - "{{ atom.url_rpm}}"
    become: yes

  when: atom_current_version.stdout == "" or atom_current_version.stdout is version(atom.version, '<')