---
- name: install the rpmfusion repo packages
  dnf: 
    name: '{{ item }}'
    state: present  
  with_items:
    - https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ fedora.version }}.noarch.rpm
    - https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ fedora.version }}.noarch.rpm
  when: ansible_os_family == "RedHat"
  become: yes
