---

- name: Create Docker group
  group:
    name: docker
    state: present
  become: yes

- name: Add current user to Docker group
  user:
    name: "{{ ansible_env.USER }}" 
    groups: docker
    append: yes
  become: yes
