---
- name: Ensure pre-requisite packages are installed for docker_compose.
  package:
    name: '{{ item }}'
    state: present
  become: yes
  with_items:
    - python-pip
    - docker-compose

# - name: Check current docker-compose version.
#   command: docker-compose --version
#   register: dc_current_version
#   changed_when: false
#   failed_when: false

# - name: Check if need update.
#   set_fact:
#     docker_compose_update: true
#   when: dc_current_version.stdout is defined
#     and docker_compose.version not in dc_current_version.stdout

# - name: Delete existing docker-compose version if it's different.
#   file:
#     path: "{{ docker_compose.path }}"
#     state: absent
#   when: docker_compose_update is defined
#   become: yes

# - name: Install docker-compose
#   get_url: 
#     url: "https://github.com/docker/compose/releases/download/{{docker_compose.version}}/docker-compose-Linux-x86_64" 
#     dest: "{{docker_compose.path}}"
#     force: no 
#     mode: 0755
#   when: docker_compose_update is defined
#   become: yes
