---

# Setup/install tasks.
- include: setup-{{ ansible_distribution }}.yml
- include: docker-compose-{{ ansible_distribution }}.yml
- include: docker-group.yml

- name: "Ensure Docker is restarted"
  command: /bin/true
  notify: Restart Docker
