---

- name: check version of docker
  shell: docker --version 2>&1 | grep -v not | sed -e 's/,//' | awk '{print $3}'
  register: current_version
  changed_when: false
  failed_when: false
  ignore_errors: true
  args:
    warn: no
  become: yes

- debug:
    msg: "Required version = {{ docker.version }} and current_version = {{ current_version }}"

- block:
  - name: Ensure old versions of Docker along with its dependencies are not installed.
    package:
      name: '{{ item }}'
      state: absent
    become: yes
    with_items:
      - docker
      - docker-common
      - container-selinux
      - docker-selinux
      - docker-engine

  - name: Add Docker GPG key.
    rpm_key:
      key: https://download.docker.com/linux/centos/gpg
      state: present
    become: yes

  - name: Add Docker repository.
    get_url:
      url: "https://download.docker.com/linux/fedora/docker-ce.repo"
      dest: '/etc/yum.repos.d/docker-ce.repo'
      owner: root
      group: root
      mode: 0644
    become: yes

  - name: Remove devicemapper folder
    file:
      path: "/var/lib/docker/devicemapper/devicemapper"
      state: absent

  - name: Create /etc/docker
    file:
      path: /etc/docker
      state: directory
    become: yes

  - name: "Configuring docker daemon"
    template:
      src: daemon.json.j2
      dest: /etc/docker/daemon.json
      mode: 0411
    become: yes

  - name: Install Docker.
    package: name=docker-ce state=present
    become: yes

  when: 
    - current_version is succeeded
    - current_version is defined
    - current_version.stdout == "" or current_version.stdout is version(docker.version, operator='<', strict=True)
