---
- hosts: localhost
  connection: local

  vars_files:
    - config.yml

  pre_tasks:
    - include_vars: "{{ item }}"
      with_fileglob:
        - config.yml
      tags: ['always']

  roles:
    - role: common
    - role: motd
    - role: rpmfusion
    - role: docker
    - role: bash-custom
    - role: virtualbox
    - role: vagrant

  tasks:
    - include: tasks/ansible-setup.yml
    - include: tasks/cleanup.yml

  handlers:
   - include: handlers/system.yml
   - include: handlers/services.yml
